version: '3'
services:
    client:
        build: ./client
        ports:
        - "8080:8080"
        volumes:
        - ./client:/ceapp/client
    server:
        build: ./server
        command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
        ports:
        - "3000:3000"
        volumes:
        - ./server:/ceapp/server
        depends_on:
        - db
    db:
        image: postgres
        volumes:
        - ./server/tmp/db:/var/lib/postgresql/
